[package]
name = "panther_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "panther_core"
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[dependencies]
once_cell = "1.21.3"
pyo3 = {version = "0.20.2", features = ["extension-module"]}
rand = "0.8.5"
