site_name: Panther
site_description: Fast &  Friendly, Web Framework For Building Async APIs
site_url: https://pantherpy.github.io

repo_name: AliRn76/Panther
repo_url: https://github.com/AliRn76/Panther
edit_uri: edit/master/docs/

theme:
  name: 'material'
  custom_dir: docs
  palette:
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      primary: 'blue'
      toggle:
        icon: 'material/lightbulb'
        name: 'Switch to dark mode'
    - scheme: 'slate'
      media: '(prefers-color-scheme: dark)'
      primary: 'blue'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'
  features:
    - navigation.path
    - navigation.footer
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

nav:
  - Introduction: 'index.md'
  - How To CRUD:
      - Function Base: 'function_first_crud.md'
      - Class Base: 'class_first_crud.md'
      - Generic: 'generic_crud.md'
  - First Crud: 'first_crud.md'
  - Database: 'database.md'
  - Model: 'model.md'
  - API: 'api.md'
  - Pagination: 'pagination.md'
  - Panther ODM: 'panther_odm.md'
  - Configs: 'configs.md'
  - Redis: 'redis.md'
  - Serializer: 'serializer.md'
  - WebSocket: 'websocket.md'
  - Middlewares: 'middlewares.md'
  - Authentications: 'authentications.md'
  - Events: 'events.md'
  - URLs: 'urls.md'
  - Throttling: 'throttling.md'
  - Background Tasks: 'background_tasks.md'
#  - Caching: 'caching.md'
#  - UserModel: 'user_model.md'
  - Single-File: 'single_file.md'
  - Monitoring: 'monitoring.md'
  - Log Queries: 'log_queries.md'
  - Open API (Swagger): 'open_api.md'
  - Roadmap: 'roadmap.md'
  - Release Notes: 'release_notes.md'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: "#"