site_name: Panther
site_description: Fast &  Friendly, Web Framework For Building Async APIs
site_url: https://pantherpy.github.io

repo_name: AliRn76/Panther
repo_url: https://github.com/AliRn76/Panther
edit_uri: edit/master/docs/

theme:
  name: 'material'
  custom_dir: docs
  palette:
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      primary: 'blue'
      toggle:
        icon: 'material/lightbulb'
        name: 'Switch to dark mode'
    - scheme: 'slate'
      media: '(prefers-color-scheme: dark)'
      primary: 'blue'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'
  features:
    - navigation.path
    - navigation.footer
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

nav:
  - Introduction: 'index.md'
  - First CRUD: 'first_crud.md'
  - Database: 'database.md'
  - Query: 'query.md'
  - URLs: 'urls.md'
  - Models: 'model.md'
  - Serializers: 'serializer.md'
  - APIs: 'api.md'
  - Redis: 'redis.md'
  - Events: 'events.md'
  - Background Tasks: 'background_tasks.md'
  - WebSocket: 'websocket.md'
  - Middlewares: 'middlewares.md'
  - Authentications: 'authentications.md'
  - Single-File Application: 'single_file.md'
  - Cross-Origin Resource Sharing (CORS): 'cors.md'
#  - Generic APIs: 'generic_api.md'  # TODO
#  - Pagination: 'pagination.md'  # TODO: Maybe we have to move it inside generics ... or somewhere else
#  - Open API (Swagger): 'open_api.md'  # TODO
  - Advance Configs:
      - User Model: 'user_model.md'
      - Timezone: 'timezone.md'
      - Auto-Reformatting (Ruff): 'ruff.md'
      - Log Queries: 'log_queries.md'
      - Template Response: 'templates.md'
      - Admin Panel: 'admin_panel.md'
  - Roadmap: 'roadmap.md'
  - Release Notes: 'release_notes.md'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: "#"